Cyware Submission - CAR-2021-01-001
mitre-attack/car pull request #79
Opened 2021-01-06 21:18 UTC by ikiril01

Submitted by Cyware Labs. Thanks to @kp625544 and team!

2021-01-08 15:21 UTC, pcmcpherson requested changes
Hi, thanks for the PR. Sorry for takin so long to get back to you; we've been understaffed in this department recently. 
Just a couple general comments: 
1. Make sure you validate your YAML syntax using a yaml linter/validator. 
2. You don't need to submit the .md file for each analytic; just the yaml will do. Our process will convert the yaml into .md for the website.

2021-01-08 15:21 UTC, pcmcpherson commented on analytics/CAR-2021-01-001.yaml
> +title: Identifying Internal hosts and services for lateral movement
Title is too long and vague; change to "Port scanning activity"

2021-01-08 15:21 UTC, pcmcpherson commented on analytics/CAR-2021-01-001.yaml
> +    sourcetype='firewall_logs' dest_ip = 'internal_subnet' | stats dc(dest_port) as pcount by source_ip | where pcount >5
source_ip should be src_ip, the standard fieldname in Splunk

2021-01-08 15:21 UTC, pcmcpherson commented on analytics/CAR-2021-01-001.yaml
> +  - flow/stop/dest_ip
remove this line, as CAR does not have this field, and we're not using it in this analytic.

2021-01-13 08:48 UTC, kp625544 commented
Changes submitted in PR - https://github.com/mitre-attack/car/pull/90

2021-02-04 22:02 UTC, pcmcpherson approved these changes

2021-02-04 22:02 UTC, merged