Cyware Submission - CAR-2021-01-006
mitre-attack/car pull request #84
Opened 2021-01-06 21:21 UTC by ikiril01

Submitted by Cyware Labs. Thanks to @kp625544 and team!

2021-01-08 16:42 UTC, pcmcpherson requested changes

2021-01-08 16:42 UTC, pcmcpherson commented on analytics/CAR-2021-01-006.yaml
> +    index = * ParentImage="*excel.exe*" Image="*.exe" | table _raw, ParentImage, Image
This analytic purports to be looking for arbitrary commands via DDE, but the splunk query is simply looking for instances of excel.exe. My guess is that this was a mistake; please fix and modify the PR. Thanks.

2021-02-08 15:41 UTC, kp625544 commented on analytics/CAR-2021-01-006.yaml
> +    index = * ParentImage="*excel.exe*" Image="*.exe" | table _raw, ParentImage, Image
Hello @pcmcpherson we are looking for any exe spawns in this in the Image parameter with the Parent Image being Excel.exe. Let me know if anything needs to be changed here

2021-03-23 14:11 UTC, pcmcpherson approved these changes

2021-03-23 14:11 UTC, merged